stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.12
      shellScript: |-
        go build -o bin/service
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: service-discovery:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification:
  recipients:
  - recipient: '#general'
    notifier: c-nhgtx:n-cxvhn
  condition:
  - Success
  - Changed
  - Failed
