kind: Service
apiVersion: v1
metadata:
  name: service-discovery

spec:
  selector:
    app: service-discovery
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  labels:
    app: service-discovery

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery

    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: service-discovery
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "./"
      volumes:
        - name: conig
          configMap:
            name: service-discovery-config
            items:
              - key: config.yaml
                path: config.yaml
